#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');

program
  .version('0.0.1')
  .option('-a, --add', 'Add numbers')
  .option('-p, --peppers', 'Add peppers')
  .option('-P, --pineapple', 'Add pineapple')
  .option('-b, --bbq', 'Add bbq sauce')
  .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')
  .parse(process.argv);

console.log('you ordered a pizza with:');
if (program.peppers) console.log('  - peppers');
if (program.pineapple) console.log('  - pineapple');
if (program.bbq) console.log('  - bbq');
console.log('  - %s cheese', program.cheese);

if (program.add) {
  // program.args is the stuff that remains after commander has parsed
  // all of the options out of process.argv. for more info, see the
  // _Option parsing_ section of commander's documentation.
  var numbers = program.args;
  var firstNumber = parseInt(numbers[0]);
  var secondNumber = parseInt(numbers[1]);
  var sum = firstNumber + secondNumber;
  // %d means show me a digit. each %thing will look for the next argument
  // after the string and use that to replace the %thing before logging.
  console.log('the sum of %d and %d is %d', firstNumber, secondNumber, sum);
}